apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-dumper
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-dump-reader
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io", "policy", "rbac.authorization.k8s.io", "autoscaling"]
    resources: ["*"]
    verbs: ["get", "list", "describe"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-dump-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-dump-reader
subjects:
  - kind: ServiceAccount
    name: k8s-dumper
    namespace: default
